@startuml
title 测试企业微信 添加成员

participant 主页面 as main

participant 通讯录 as contact

participant 添加成员 as add_member

participant 手动输入添加成员页面 as add_member_of_sd

autonumber

main -> contact : 点击通讯录按钮

contact -> add_member : 滑动查找添加成员按钮

add_member -> add_member_of_sd : 点击手动添加

add_member_of_sd -> contact : 查找是否添加成员成功

@enduml