# NOTE: Generated By HttpRunner v3.1.5
# FROM: .\har\mubu1.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu1(HttpRunner):

    config = Config("testcase description").verify(False).variables(**{
        # 全局变量
    })

    teststeps = [
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
                    "data-unique-id": "818ddb93-8827-4277-b011-f176a74251a7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI1MDQwMDYiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjczNTU0NjAsImlhdCI6MTYyNDc2MzQ2MH0.6bGHlgzcrfRZiBhADnEaI1dF7l-AdhzMaK57JkJu-kcGYymomboRzGs_iRecSgt21UndxpuPg5dKYtJcdnxEoA",
                    "x-request-id": "0b858276-ffa1-4cfe-9ce1-42ff43684dd1",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"name": "1234", "folderId": "0"})
            .extract()
            .with_jmespath("body.data.folder.id", "folderId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "35",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
                    "data-unique-id": "818ddb93-8827-4277-b011-f176a74251a7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI1MDQwMDYiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjczNTU0NjAsImlhdCI6MTYyNDc2MzQ2MH0.6bGHlgzcrfRZiBhADnEaI1dF7l-AdhzMaK57JkJu-kcGYymomboRzGs_iRecSgt21UndxpuPg5dKYtJcdnxEoA",
                    "x-request-id": "1307a7a1-274a-4ef4-9386-38f00718fbb3",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "type": 0})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu1().test_start()
