# Generated by Django 3.2.6 on 2021-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='新建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('report', models.CharField(max_length=255, verbose_name='报告地址')),
            ],
            options={
                'verbose_name_plural': '任务表',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='新建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, verbose_name='用例名字')),
                ('nodeId', models.CharField(max_length=20, verbose_name='node id')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '用例表',
            },
        ),
    ]
