# Generated by Django 3.2.6 on 2021-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='新建时间'),
        ),
    ]
